# coding: utf-8

"""
    kubidm

    API for interacting with the kubidm system. This is a work in progress.

    The version of the OpenAPI document: 1.9.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from kubidm_openapi_client.models.credential_detail import CredentialDetail
from kubidm_openapi_client.models.passkey_detail import PasskeyDetail
from typing import Optional, Set
from typing_extensions import Self

class CredentialStatus(BaseModel):
    """
    CredentialStatus
    """ # noqa: E501
    creds: List[CredentialDetail]
    passkeys: Optional[List[PasskeyDetail]] = None
    attested_passkeys: Optional[List[PasskeyDetail]] = None
    __properties: ClassVar[List[str]] = ["creds", "passkeys", "attested_passkeys"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CredentialStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in creds (list)
        _items = []
        if self.creds:
            for _item_creds in self.creds:
                if _item_creds:
                    _items.append(_item_creds.to_dict())
            _dict['creds'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in passkeys (list)
        _items = []
        if self.passkeys:
            for _item_passkeys in self.passkeys:
                if _item_passkeys:
                    _items.append(_item_passkeys.to_dict())
            _dict['passkeys'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attested_passkeys (list)
        _items = []
        if self.attested_passkeys:
            for _item_attested_passkeys in self.attested_passkeys:
                if _item_attested_passkeys:
                    _items.append(_item_attested_passkeys.to_dict())
            _dict['attested_passkeys'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CredentialStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creds": [CredentialDetail.from_dict(_item) for _item in obj["creds"]] if obj.get("creds") is not None else None,
            "passkeys": [PasskeyDetail.from_dict(_item) for _item in obj["passkeys"]] if obj.get("passkeys") is not None else None,
            "attested_passkeys": [PasskeyDetail.from_dict(_item) for _item in obj["attested_passkeys"]] if obj.get("attested_passkeys") is not None else None
        })
        return _obj
