[package]
name = "kubidm_unix_int"
description = "Kanidm Unix Integration and Identity Resolver"

version = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[features]
default = ["unix"]
unix = []
selinux = ["sparkle_resolver_common/selinux"]
tpm = ["sparkle_resolver_common/tpm"]
dhat-heap = ["sparkle_resolver_common/dhat-heap"]
dhat-ad-hoc = ["sparkle_resolver_common/dhat-ad-hoc"]

[lib]
name = "kubidm_flavour"
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "kubidm_unixd"
path = "src/bin/kubidm_unixd.rs"
required-features = ["unix"]
test = false
doctest = false

[[bin]]
name = "kubidm_unixd_tasks"
path = "src/bin/kubidm_unixd_tasks.rs"
required-features = ["unix"]
test = false
doctest = false

[[bin]]
name = "kubidm_ssh_authorizedkeys"
path = "src/bin/kubidm_ssh_authorizedkeys.rs"
required-features = ["unix"]
test = false
doctest = false

[[bin]]
name = "kubidm-unix"
path = "src/bin/kubidm-unix.rs"
required-features = ["unix"]
test = false
doctest = false

[dependencies]
sparkle_resolver_common = { workspace = true }
tokio = { workspace = true, features = [
    "rt",
    "rt-multi-thread",
    "fs",
    "macros",
    "sync",
    "time",
    "net",
    "io-util",
] }

[build-dependencies]
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
kubidm_build_profiles = { workspace = true }
sparkle_resolver_common = { workspace = true }

## Debian packaging
# We only package unixd itself here as shared libraries must be packaged separarately due to multiarch rules.
[package.metadata.deb]
name = "kubidm-unixd"
maintainer = "James Hodgkinson <james@terminaloutcomes.com>"
depends = [
	"libc6",
	"tpm-udev",
	"libpam-kubidm",
	"libnss-kubidm"
]
section = "network"
priority = "optional"
changelog = "../../target/debian/changelog"  # Generated by platform/debian/build_debs.sh
assets = [
    [ "target/release/kubidm_ssh_authorizedkeys", "usr/sbin/", "755" ],
    [ "target/release/kubidm_unixd_tasks", "usr/sbin/", "755" ],
    [ "target/release/kubidm_unixd", "usr/sbin/", "755" ],
    [ "target/release/kubidm-unix", "usr/sbin/", "755" ],
    [ "../../examples/unixd-safe-default", "etc/kubidm/unixd", "644" ],
    [ "../../examples/kubidm-safe-default", "etc/kubidm/config", "644" ],
    [ "../../examples/kubidm", "usr/share/kubidm-unixd/", "444" ],
    [ "../../examples/unixd", "usr/share/kubidm-unixd/", "444" ],
    [ "../../examples/sshd-config.conf", "etc/ssh/sshd_config.d/10-kubidm.conf", "644"],
]
maintainer-scripts = "debian/"
systemd-units = [
	{ unit-name = "kubidm-unixd", enable = true},
	{ unit-name = "kubidm-unixd-tasks", enable = true},
]

[package.metadata.cargo-machete]
ignored = ["kubidm_build_profiles", "clap_complete"]

