---
name: Windows Build and Test

# Trigger the workflow on push to master or pull request
"on":
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:  # so you can run it manually
env:
  RUSTC_WRAPPER: "sccache"
  KANIDM_BUILD_PROFILE: developer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows_build_kubidm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install OpenSSL
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install sccache
        run: |
          $url = "https://github.com/mozilla/sccache/releases/download/v0.15.0/sccache-v0.15.0-x86_64-pc-windows-msvc.tar.gz"
          Invoke-WebRequest -Uri $url -OutFile sccache.tar.gz
          tar -xzf sccache.tar.gz
          Move-Item -Path "sccache-v0.15.0-x86_64-pc-windows-msvc/sccache.exe" -Destination "$env:USERPROFILE\.cargo\bin\sccache.exe"
          New-Item -ItemType Directory -Force -Path "${{ runner.temp }}\sccache"
          echo "SCCACHE_DIR=${{ runner.temp }}\sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup sccache cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}\sccache
          key: sccache-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: sccache-${{ runner.os }}-
      - run: cargo build --locked -p kubidm_client -p kubidm_tools --bin kubidm
      # yamllint disable-line rule:line-length
      - run: cargo test -p kubidm_client -p kubidm_tools
